apiVersion: v1
kind: ReplicationController
metadata:
  name: myonline app
spec:
   replicas: 6
   selector:
     app: myonline app
   template:
     metadata:
       labels:
          app: myonline app
     spec:
        containers:
        - name: myonline app
          image: myonline app
          ports:
          - containerPort: 8080