apiVersion: v1
kind: ReplicationController
metadata:
  name: myonline app
spec:
   replicas: 6
   selector:
     app: myonline app
   template:
     metadata:
       labels:
          app: myjenkins-pod
     spec:
        containers:
        - name: myonline app
          image: jenkins:2.60.3
          ports:
          - containerPort: 8080