apiVersion: v1
kind: Service
metadata:
  name: myonline app
  labels:
     app: myonline app
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
      app: myonline app